name: 🧪 Test
description: Unit test for this project
title: "test(): title"
labels: [test]
assignees:
  - argozhang
body:
- type: textarea
  attributes:
    label: Which class is this unit test associated with?
    description: Add unit test for code coverage.
    value: Improve code coverage
  validations:
    required: false
