name: Close inactive issues
on:
  schedule:
    - cron: "30 2 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 2
          days-before-issue-close: 2
          stale-issue-label: "stale"
          stale-issue-message: "Since the issue was labeled with `invalid`, but no response in 2 days. This issue will be closed. If you have any questions, you can comment and reply. 由于该 issue 被标记为不合规工程，却 2 天未收到回应。现关闭 issue，若有任何问题，可评论回复"
          close-issue-message: "Since the issue was labeled with `need-repro-project`, but no response in 2 days. This issue will be closed. If you have any questions, you can comment and reply. 由于该 issue 被标记为需要复现工程，却 2 天未收到回应。现关闭 issue，若有任何问题，可评论回复"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
